### ISSUE TITLE
Huge performance drops on some beatmaps

### ISSUE THREAD

**Issue by kionell** [blueberrymuffin3/osu-js#7] opened 2022-07-20 13:51 UTC
Here are some beatmaps that can lead to performance issues:

1) https://osu-js.pages.dev/play/?1006822 - This one has a really complex storyboard. I have low FPS on both PC and mobile Chrome (which is not much different from the game itself with its 30 fps). Also, it looks like some of the assets are overlaid with gray background. In fact, osu! hides background image if storyboard is enabled. Maybe you should also consider locking the aspect ratio of the page, because some elements might not render correctly, like the bottom of the screenshot below.
![World execute render](https://user-images.githubusercontent.com/43014304/179995861-19b45cca-3ebe-4220-8187-be24984f5b96.PNG)
 
2) https://osu-js.pages.dev/play/?3169451 - This is my favourite stress test beatmap. It has super weird sliders in the second half of the beatmap. Last time when i tried to render them, my browser hung almost instantly :D

## Sub-Issues:
- [ ] #12
- [x] #13
- [x] #18

**Comment by blueberrymuffin3** [comment] 2022-07-20 20:04
The first map's issues are most likely because of the WIP storyboard renderer. IDK if osu-js will ever have "good" performance for that map, though.

The hang in the second map seems to be caused by the sliders being so large, that the texture allocated to render them exceeds the 16384x16384 texture limit of many GPU's. I'll look into that. It seems to break the autoplay, but I guess that's to be expected, lol.

**Comment by blueberrymuffin3** [comment] 2022-07-25 02:31
@kionell Can you test [world.execute(me);](https://osu-js.pages.dev/play/?1006822) again on your devices? I've greatly optimized the storyboard, and am able to maintain 100+ average FPS with 20 FPS on the complex parts.

**Comment by kionell** [comment] 2022-07-25 08:57
@blueberrymuffin3 Overall FPS is much better now, but the storyboard stopped rendering on my phone. I assume it happened after [this](https://github.com/blueberrymuffin3/osu-js/commit/d18869ca8fe32952b776f649594dc819b688a85c) commit.

**Comment by blueberrymuffin3** [comment] 2022-07-26 01:44
@kionell The regression that caused the storyboard to stop rendering on some phones should be fixed now, can you confirm if it works?

**Comment by kionell** [comment] 2022-07-26 02:37
@blueberrymuffin3 Yep, it works as it should.

**Closed as completed** 2022-07-26 05:16 UTC
Labels: meta

**Comment by blueberrymuffin3** [comment] 2022-07-26 05:19
@kionell The crash caused by the slider art should be fixed now
